# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LOCATION": "configs.ipynb",
         "find_links_in_markdown_text": "utility.markdown.ipynb",
         "link_with_anchor": "utility.markdown.ipynb",
         "get_formatted_markdown_link": "utility.markdown.ipynb",
         "WEBSITE_URL": "utility.markdown.ipynb",
         "replace_all_links_with_formatted_links": "utility.markdown.ipynb",
         "find_footnotes_in_markdown_text": "utility.markdown.ipynb",
         "replace_all_footnotes_with_formatted_footnotes": "utility.markdown.ipynb",
         "embed_markdown_file": "utility.markdown.ipynb",
         "replace_string_by_indices": "utility.string.ipynb"}

modules = ["configs.py",
           "definition/limit.py",
           "definition/real_valued_function.py",
           "definition/set.py",
           "notation/basic.py",
           "notation/calculus.py",
           "utility/markdown.py",
           "utility/string.py"]

doc_url = "https://Hyun Jong Kim.github.io/mathbook/"

git_url = "https://github.com/Hyun Jong Kim/mathbook/tree/master/"

def custom_doc_links(name): return None
