# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"embed_markdown_file": "utility.markdown.ipynb",
         "find_links_in_markdown_text": "utility.markdown.ipynb",
         "replace_string_by_indices": "utility.string.ipynb"}

modules = ["definition/limit.py",
           "definition/real_valued_function.py",
           "utility/markdown.py",
           "utility/string.py"]

doc_url = "https://Hyun Jong Kim.github.io/mathbook/"

git_url = "https://github.com/Hyun Jong Kim/mathbook/tree/master/"

def custom_doc_links(name): return None
