# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/configs.ipynb (unless otherwise specified).

__all__ = ['LOCATION']

# Cell
# to use these variables, first run ``nbdev_build_lib`` and then import using ``from mathbook.configs import <variable>``
LOCATION = 'website'