# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/notation.basic.ipynb (unless otherwise specified).

__all__ = []

# Cell
if __name__ == '__main__': embed_markdown_file('notation.set_membership.md', location='notebook')