# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/notation.calculus.ipynb (unless otherwise specified).

__all__ = []

# Cell
if __name__ == '__main__':
    embed_markdown_file('notation.real_valued_function.md',
                        destination=DESTINATION, origin=ORIGIN)