# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utility.markdown.ipynb (unless otherwise specified).

__all__ = ['embed_markdown_file', 'find_links_in_markdown_text']

# Cell
from IPython.display import display, Markdown
import os.path
from pathlib import Path
import urllib.parse

# Cell
def embed_markdown_file(file_path, display_file_link=False):
    """Embed markdown file content into ipynb.
    """

    with open(file_path, 'r') as markdown_file:
        text = markdown_file.read()
        display(Markdown(text))
        markdown_file.close()

# Cell
def find_links_in_markdown_text(file_path):
    """Return ranges in the markdown text string where links occur.
    """
