# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/definition.function.ipynb (unless otherwise specified).

__all__ = []

# Cell
if __name__ == '__main__':
    embed_markdown_file('definition.function.md',
                        destination=DESTINATION, origin=ORIGIN)