# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/definition.function_defined_near_a_point.ipynb (unless otherwise specified).

__all__ = []

# Cell
if __name__ == '__main__':
    embed_markdown_file('definition.real_valued_function_continuous_at_a_point.md',
                        destination=DESTINATION, origin=NOTEBOOK)

# Cell
if __name__ == '__main__':
    embed_markdown_file('definition.function_defined_near_a_point.md',
                        destination=DESTINATION, origin=ORIGIN)