# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/definition.limit.ipynb (unless otherwise specified).

__all__ = []

# Cell
if __name__ == '__main__': embed_markdown_file('limit_of_a_function_at_a_finite_input.md')