# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/definition.limit.ipynb (unless otherwise specified).

__all__ = []

# Cell
from ..utility.markdown import *

# Cell
embed_markdown_file('limit_of_a_function_at_a_finite_input.md')