# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/definition.real_valued_function.ipynb (unless otherwise specified).

__all__ = []

# Cell
if __name__ == '__main__': embed_markdown_file('real_valued_function.md')