# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/definition.real_numbers.ipynb (unless otherwise specified).

__all__ = []

# Cell
if __name__ == '__main__':
    embed_markdown_file('definition.real_numbers.md',
                        origin=ORIGIN, destination=DESTINATION)