# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/definition.real_valued_function.ipynb (unless otherwise specified).

__all__ = []

# Cell
from ..utility.markdown import *

# Cell
embed_markdown_file('real_valued_function.md')