# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/definition.subset.ipynb (unless otherwise specified).

__all__ = []

# Cell
if __name__ == '__main__':
    embed_markdown_file('definition.subset.md',
                        origin=ORIGIN, destination=DESTINATION)